### ISSUE TITLE
Unable to compile MOM6 from ufs-weather-model with WCOSS2 spack-stack/1.9.2

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [ufs-community/ufs-weather-model#2825]
## Description

GDASApp builds soca using code from ufs weather model interfaces to CICE and MOM6
```
ufs_model.fd/CICE-interface/CICE/icepack/
ufs_model.fd/MOM6-interface/MOM6/
```
The WCOSS2 build of GDASApp using spack-stack/1.9.2 aborts when compiling `MOM6/src/tracer/MARBL_tracers.F90`
```
          #0 0x000000000312d792
          #1 0x0000000003191e57
          #2 0x0000000003191f80
          #3 0x0000147498c53d70
          #4 0x00000000030f62bf
          #5 0x00000000030f6220
          #6 0x00000000030f6220
          #7 0x00000000030f5fbe
          #8 0x00000000030cbccc
          #9 0x000000000307863e
         #10 0x000000000324df17
         #11 0x0000147498c3e1fd __libc_start_main + 239
         #12 0x0000000002eb06ea

/tmp/ifx15573604536oQD4K/ifxhZ9E0K.i90: error #5633: **Internal compiler error: segmentation violation signal raised** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/bundle/soca/external/mom6/MOM6/src/tracer/MARBL_tracers.F90 (code 3)
```  
## Solution
GDASApp builds with spack-stack/1.9.2 on Gaea C6, Hera, Hercules, Orion, and Ursa.  Therefore, suspect the issue is with the WCOSS2 spack-stack/1.9.2 installation and not GDASApp or ufs-weather-model.

Has the ufs-weather-model been successfully built on WCOSS2 using spack-stack/1.9.2?

## Alternatives
None

## Related to
- required to support https://github.com/NOAA-EMC/GDASApp/issues/1809
- needed by https://github.com/NOAA-EMC/global-workflow/pull/3798

**Comment by BrianCurtis-NOAA** [comment]
Is there a WCOSS2 official or unofficial spack-stack 1.9.2 installation somewhere?

I'm only familiar with the updated libraries (the D suite) that match better with what's in spack-stack 1.9.2.

**Comment by RussTreadon-NOAA** [comment]
NCO and the EMC library team pointed me at the unofficial `/apps/ops/test/spack-stack-nco-1.9/modulefiles/Core` to test with the GDASApp.  I am working on Acorn in `HOMEgfs=/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192`.  Script `sorc/build_gdas.sh` is used to compile and install GDASApp.

**Comment by RussTreadon-NOAA** [comment]
**Sensitivity test**

Capture the compilation line which aborts in a shell script.  Add module load and set environment variables in script to mimic GDASApp build script.  The script only attempts to compile `MARBL_tracers.F90`.  

The script is `/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/test.sh` on Acorn.

Execute `test.sh`.  Replicate the reported compilation error
```
russ.treadon@alogin02:/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc> ./test.sh
+ HOMEgfs=/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192
+ set +x
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.

Lmod is automatically replacing "intel/19.1.3.304" with "intel-oneapi/2024.2".


Currently Loaded Modules:
  1) craype-x86-rome         (H)  15) git/2.47.0              29) boost/1.84.0                   43) gsl-lite/0.37.0    57) py-certifi/2023.7.22
  2) envvar/1.0                   16) git-lfs/3.5.1           30) ecbuild/3.7.2                  44) libjpeg/2.1.0      58) py-netcdf4/1.7.1.post2
  3) PrgEnv-intel/8.3.3           17) zstd/1.5.6              31) eigen/3.4.0                    45) libpng/1.6.37      59) py-pyyaml/6.0.2
  4) intel-oneapi/2024.2          18) pigz/2.8                32) openblas/0.3.24                46) libxt/1.3.0        60) py-setuptools/63.4.3
  5) stack-oneapi/2024.2.1        19) tar/1.34                33) eckit/1.28.3                   47) libxmu/1.2.1       61) py-tzdata/2023.3
  6) libfabric/1.20.1             20) gettext/0.22.5          34) fckit/0.13.2                   48) libxpm/3.5.17      62) py-pytz/2023.3
  7) craype-network-ofi      (H)  21) curl/8.10.1             35) fms/2024.02                    49) libxaw/1.0.16      63) py-six/1.16.0
  8) cray-mpich/8.1.29            22) hdf5/1.14.3             36) python-venv/1.0                50) udunits/2.2.28     64) py-python-dateutil/2.8.2
  9) stack-cray-mpich/8.1.29      23) parallel-netcdf/1.12.3  37) intel-oneapi-runtime/2024.2.1  51) ncview/2.1.9       65) py-pandas/2.2.3
 10) python/3.11.7                24) netcdf-c/4.9.2          38) glibc/2.31                     52) netcdf-cxx4/4.3.1  66) py-packaging/24.1
 11) stack-python/3.11.7          25) nccmp/1.9.0.1           39) esmf/8.6.1                     53) prod_util/2.0.14   67) py-xarray/2024.7.0
 12) cmake/3.27.9                 26) netcdf-fortran/4.6.1    40) atlas/0.40.0                   54) py-numpy/1.26.4    68) py-pip/23.1.2
 13) craype/2.7.17                27) nco/5.2.4               41) sp/2.5.0                       55) bufr/12.1.0        69) rocoto/1.3.5
 14) cray-pals/1.3.2              28) parallelio/2.6.2        42) ip/5.1.0                       56) py-cftime/1.0.3.4  70) GDAS/wcoss2.intel

  Where:
   H:  Hidden Module

 

+ export LMOD_MPI_NAME=cray-mpich
+ LMOD_MPI_NAME=cray-mpich
+ export LMOD_MPI_VERSION=8.1.29-xhbciau
+ LMOD_MPI_VERSION=8.1.29-xhbciau
+ cd /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/build/soca/external/mom6
+ /opt/cray/pe/craype/2.7.17/bin/ftn --version
ifx (IFX) 2024.2.1 20240711
Copyright (C) 1985-2024 Intel Corporation. All rights reserved.

+ /opt/cray/pe/craype/2.7.17/bin/ftn -DNDEBUG -DSPMD -Duse_libMPI -Duse_netCDF -I/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/build/soca/external/mom6/mod -I/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/bundle/soca/external/mom6/MOM6/config_src/memory/dynamic_nonsymmetric -I/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/bundle/soca/external/mom6/MOM6/src/framework -I/apps/ops/test/spack-stack-nco-1.9/oneapi/2024.2.1/netcdf-c-4.9.2-zjvomwn/include -I/apps/ops/test/spack-stack-nco-1.9/oneapi/2024.2.1/netcdf-fortran-4.6.1-oykkcn7/include -I/apps/ops/test/spack-stack-nco-1.9/oneapi/2024.2.1/netcdf-cxx4-4.3.1-cwdoxwa/include -I/apps/ops/test/spack-stack-nco-1.9/oneapi/2024.2.1/fms-2024.02-jm3mxir/include_r8 -gcc-name=/opt/cray/pe/gcc/12.1.0/snos/bin/gcc -gxx-name=/opt/cray/pe/gcc/12.1.0/snos/bin/g++ -qopenmp-stubs -g -traceback -i4 -r8 -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -sox -O2 -g -module mod -fPIC -fiopenmp -c /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/bundle/soca/external/mom6/MOM6/src/tracer/MARBL_tracers.F90 -o CMakeFiles/mom6.dir/MOM6/src/tracer/MARBL_tracers.F90.o
ifx: command line warning #10148: option '-sox' not supported
ifx: command line warning #10121: overriding '-qopenmp-stubs' with '-fiopenmp'
          #0 0x000000000312d792
          #1 0x0000000003191e57
          #2 0x0000000003191f80
          #3 0x0000145ee0853d70
          #4 0x00000000030f62bf
          #5 0x00000000030f6220
          #6 0x00000000030f6220
          #7 0x00000000030f5fbe
          #8 0x00000000030cbccc
          #9 0x000000000307863e
         #10 0x000000000324df17
         #11 0x0000145ee083e1fd __libc_start_main + 239
         #12 0x0000000002eb06ea

/tmp/ifx1524631235i0AYRW/ifxVNE6xX.i90: error #5633: **Internal compiler error: segmentation violation signal raised** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/bundle/soca/external/mom6/MOM6/src/tracer/MARBL_tracers.F90 (code 3)
```

Add 
```
export INTEL_COMPILER_TYPE=CLASSIC
```
before executing `/opt/cray/pe/craype/2.7.17/bin/ftn`.  Rerun the script.  Compilation was successful
```
russ.treadon@alogin02:/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc> ./test.sh
+ HOMEgfs=/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192
+ set +x
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.

Lmod is automatically replacing "intel/19.1.3.304" with "intel-oneapi/2024.2".


Currently Loaded Modules:
  1) craype-x86-rome         (H)  15) git/2.47.0              29) boost/1.84.0                   43) gsl-lite/0.37.0    57) py-certifi/2023.7.22
  2) envvar/1.0                   16) git-lfs/3.5.1           30) ecbuild/3.7.2                  44) libjpeg/2.1.0      58) py-netcdf4/1.7.1.post2
  3) PrgEnv-intel/8.3.3           17) zstd/1.5.6              31) eigen/3.4.0                    45) libpng/1.6.37      59) py-pyyaml/6.0.2
  4) intel-oneapi/2024.2          18) pigz/2.8                32) openblas/0.3.24                46) libxt/1.3.0        60) py-setuptools/63.4.3
  5) stack-oneapi/2024.2.1        19) tar/1.34                33) eckit/1.28.3                   47) libxmu/1.2.1       61) py-tzdata/2023.3
  6) libfabric/1.20.1             20) gettext/0.22.5          34) fckit/0.13.2                   48) libxpm/3.5.17      62) py-pytz/2023.3
  7) craype-network-ofi      (H)  21) curl/8.10.1             35) fms/2024.02                    49) libxaw/1.0.16      63) py-six/1.16.0
  8) cray-mpich/8.1.29            22) hdf5/1.14.3             36) python-venv/1.0                50) udunits/2.2.28     64) py-python-dateutil/2.8.2
  9) stack-cray-mpich/8.1.29      23) parallel-netcdf/1.12.3  37) intel-oneapi-runtime/2024.2.1  51) ncview/2.1.9       65) py-pandas/2.2.3
 10) python/3.11.7                24) netcdf-c/4.9.2          38) glibc/2.31                     52) netcdf-cxx4/4.3.1  66) py-packaging/24.1
 11) stack-python/3.11.7          25) nccmp/1.9.0.1           39) esmf/8.6.1                     53) prod_util/2.0.14   67) py-xarray/2024.7.0
 12) cmake/3.27.9                 26) netcdf-fortran/4.6.1    40) atlas/0.40.0                   54) py-numpy/1.26.4    68) py-pip/23.1.2
 13) craype/2.7.17                27) nco/5.2.4               41) sp/2.5.0                       55) bufr/12.1.0        69) rocoto/1.3.5
 14) cray-pals/1.3.2              28) parallelio/2.6.2        42) ip/5.1.0                       56) py-cftime/1.0.3.4  70) GDAS/wcoss2.intel

  Where:
   H:  Hidden Module

 

+ export LMOD_MPI_NAME=cray-mpich
+ LMOD_MPI_NAME=cray-mpich
+ export LMOD_MPI_VERSION=8.1.29-xhbciau
+ LMOD_MPI_VERSION=8.1.29-xhbciau
+ export INTEL_COMPILER_TYPE=CLASSIC
+ INTEL_COMPILER_TYPE=CLASSIC
+ cd /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/build/soca/external/mom6
+ /opt/cray/pe/craype/2.7.17/bin/ftn --version
ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.
ifort (IFORT) 2021.13.1 20240703
Copyright (C) 1985-2024 Intel Corporation.  All rights reserved.

+ /opt/cray/pe/craype/2.7.17/bin/ftn -DNDEBUG -DSPMD -Duse_libMPI -Duse_netCDF -I/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/build/soca/external/mom6/mod -I/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/bundle/soca/external/mom6/MOM6/config_src/memory/dynamic_nonsymmetric -I/lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/bundle/soca/external/mom6/MOM6/src/framework -I/apps/ops/test/spack-stack-nco-1.9/oneapi/2024.2.1/netcdf-c-4.9.2-zjvomwn/include -I/apps/ops/test/spack-stack-nco-1.9/oneapi/2024.2.1/netcdf-fortran-4.6.1-oykkcn7/include -I/apps/ops/test/spack-stack-nco-1.9/oneapi/2024.2.1/netcdf-cxx4-4.3.1-cwdoxwa/include -I/apps/ops/test/spack-stack-nco-1.9/oneapi/2024.2.1/fms-2024.02-jm3mxir/include_r8 -gcc-name=/opt/cray/pe/gcc/12.1.0/snos/bin/gcc -gxx-name=/opt/cray/pe/gcc/12.1.0/snos/bin/g++ -qopenmp-stubs -g -traceback -i4 -r8 -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -sox -O2 -g -module mod -fPIC -fiopenmp -c /lfs/h2/emc/da/noscrub/russ.treadon/git/global-workflow/ss192/sorc/gdas.cd/bundle/soca/external/mom6/MOM6/src/tracer/MARBL_tracers.F90 -o CMakeFiles/mom6.dir/MOM6/src/tracer/MARBL_tracers.F90.o
ifort: remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.
ifort: command line warning #10148: option '-fiopenmp' not supported
```

**Questions**
- Does the Acorn (WCOSS2) ifx (IFX) 2024.2.1 20240711 compiler have a bug?
- Alternatively, does `MARBL_tracers.F90` contain code which does not conform to standards expected by ifx (IFX) 2024.2.1 20240711?

**Comment by RussTreadon-NOAA** [comment]
Is it sufficient to open an issue here in ufs-weather-model or should an issue also be opened in [NOAA-EMC/MOM6](https://github.com/NOAA-EMC/MOM6)?

GDASApp will be implemented as part of GFS v17.  Currently GDASApp builds and runs on WCOSS2 using a test version of spack-stack/1.6.0.  It's my understanding that spack-stack/1.9.2 or a later version will be the official production-ready version which we will need to use for GDASApp.  Hence the importance of resolving the current issue of compiling MOM6 `MARBL_tracers.F90` with spack-stack/1.9.2.

**Comment by JessicaMeixner-NOAA** [comment]
Pinging @jiandewang and @sanAkel for MOM6.   

@Hang-Lei-NOAA  - do we have all of the libraries needed to test ufs with the new spack-stack? If that's what we are going to be using in GFSv17, that seems like something we should be doing ASAP if we already need to be testing GDASApp.

**Comment by Hang-Lei-NOAA** [comment]
@JessicaMeixner-NOAA please wait to see a complete spack-stack testing version to be released on wcoss2. There are some small issues to be addressed. 

So far, there is no information that spack-stack will be used for GFSv17 for operations. For this question, it is better to check on a federal meeting. Rahul or Jacob is the better information source.

**Comment by JessicaMeixner-NOAA** [comment]
> So far, there is no information that spack-stack will be used for GFSv17 for operations. For this question, it is better to check on a federal meeting. Rahul or Jacob is the better information source.

@JacobCarley-NOAA  @aerorahul

**Comment by JacobCarley-NOAA** [comment]
Hi Everyone - the goal is to use spack-stack for operations in GFSv17. We're close to getting 1.9.2 going on wcoss2 but it's not quite ready for use. The EMC+NCO team is hoping to have something ready for a test release in a week or so. 

Tagging @AlexanderRichert-NOAA for awareness.

**Comment by jiandewang** [comment]
this marble code gave us trouble at the time when I tested the original NCAR-MOM6 PR, see
https://github.com/NOAA-EMC/MOM6/issues/144#issuecomment-2797123228
it failed to be compiled on herculus due to compile version (at that time the ifx test case was set on herculus). After discussion with EIB group we moved that test ifx test case to GAEA C5 which has a different version of ifx.

**Comment by RussTreadon-NOAA** [comment]
Thank you @jiandewang for sharing this information.  Good to know that this problem was previously encountered.

**Comment by jiandewang** [comment]
@RussTreadon-NOAA the root cause is the version of ifx.
A similar issue was reported to intel community at 
https://community.intel.com/t5/Intel-Fortran-Compiler/Internal-compiler-error-segmentation-violation-signal-raised/td-p/1590217

**Comment by jiandewang** [comment]
FYI: for UWM ifx job in rt.sh is not being tested on wcoss2

**Comment by RussTreadon-NOAA** [comment]
Given @jiandewang 's comments, add
```
setenv("FC","ifort")
```
to GDASApp `wcoss2.intel.lua`.  With this change the compilers used to build GDASApp with Cactus spack-stack/1.9.2 are
```
-- The C compiler identification is IntelLLVM 2024.2.1
-- The CXX compiler identification is IntelLLVM 2024.2.1
-- The Fortran compiler identification is Intel 2021.1.0.20240703
-- Cray Programming Environment 2.7.17 C
```

In addition to the above change to GDASApp `wcoss2.intel.lua`, the GDASApp `build.sh` includes the following local modifications:
```
  export LMOD_MPI_NAME=cray-mpich
  export LMOD_MPI_VERSION=8.1.29-xhbciau
  export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/cray/pe/mpich/8.1.29/ofi/intel/2022.1/lib"
```

One final change was to modify the `sorc/saber/CMakeLists.txt` to comment out the `find_package( atlas)` line.  When this line is present the configure fails with
```
CMake Error at saber/CMakeLists.txt:42 (find_package):
  Found package configuration file:

    /apps/ops/test/spack-stack-nco-1.9/oneapi/2024.2.1/ecmwf-atlas-0.40.0-jhtizao/lib64/cmake/atlas/atlas-config.cmake

  but it set atlas_FOUND to FALSE so package "atlas" is considered to be NOT
  FOUND.
```
The build proceeds when the `find_package` line is commented out.

With the above local modifications in place the GDASApp build ran to completion on Cactus using spack-stack/1.9.2 from `/apps/ops/test/spack-stack-nco-1.9/modulefiles/Core`.

I have not yet run any tests to confirm that the GDASApp executables work as intented.

**Comment by sanAkel** [comment]
## Question:

Are we using anything from the [MARBL tracers?](https://github.com/NOAA-EMC/MOM6/blob/f9e6e2e1686458df842a0b92c61ff241a920ed84/src/tracer/MARBL_tracers.F90#L6)

At the moment, I think the answer to ⬆️ question:
- Is `No`.
- Is there anyone who says `Yes`?

**Comment by jiandewang** [comment]
no we are not using that marble feature but the code has to be in the compiling package otherwise whole MOM6 won't be able to be compiled

**Comment by RussTreadon-NOAA** [comment]
We have a workaround for the compilation of `MOM6/src/tracer/MARBL_tracers.F90` in the GDASApp using WCOSS2 `spack-stack/1.9.2`.  

I will close this issue if no one objects.

**Comment by sanAkel** [comment]
> We have a workaround for the compilation of `MOM6/src/tracer/MARBL_tracers.F90` in the GDASApp using WCOSS2 `spack-stack/1.9.2`.  
> 
> I will close this issue if no one objects.

@RussTreadon-NOAA Are you referring to [this "workaround"](https://github.com/ufs-community/ufs-weather-model/issues/2825#issuecomment-3120178180)? 

If it builds and gives the same answers, then I have no problem!

**Comment by RussTreadon-NOAA** [comment]
Yes, @sanAkel .  This is the workaround to which I refer.  This set of changes allows the GDASApp to compile MOM6/src/tracer/MARBL_tracers.F90 on WCOSS2 using `spack-stack/1.9.2`.  

GDASApp ctests pass as documented in GDASApp PR [#1817](https://github.com/NOAA-EMC/GDASApp/pull/1817).

**Comment by sanAkel** [comment]
> Yes, @sanAkel .  This is the workaround to which I refer.  This set of changes allows the GDASApp to compile MOM6/src/tracer/MARBL_tracers.F90 on WCOSS2 using `spack-stack/1.9.2`.  
> 
> GDASApp ctests pass as documented in GDASApp PR [#1817](https://github.com/NOAA-EMC/GDASApp/pull/1817).  

In that case, I'm good with those updates. 🙏

**Comment by AlexanderRichert-NOAA** [comment]
I ran into the same issue just now-- I'll add that exporting `INTEL_COMPILER_TYPE=RECOMMENDED` tells the Cray ftn wrapper to use ifort (while cc and CC will still use icx and icpx, respectively), so I think that is the preferred way to do it.
