### ISSUE TITLE
`datm_cdeps_lm4_oneapi` compile failure on Orion w/spack-stack v2.1.0

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/ufs-weather-model#3212]
## Description
On Orion, all RT configurations compile with spack-stack v2.1.0 except `datm_cdeps_lm4_oneapi`, which fails due to errors like:
```
/work2/noaa/epic/gpetro/orion/RTs/ufs-wm/pretests/3174/LM4-driver/nuopc_cap/lm4_surface_flux.F90(5): error #6580: Name in only-list does not exist or is not accessible.   [CLOSE_FILE]
   use             fms_mod, only: close_file, mpp_pe, mpp_root_pe, write_version_number
----------------------------------^
/work2/noaa/epic/gpetro/orion/RTs/ufs-wm/pretests/3174/LM4-driver/nuopc_cap/lm4_surface_flux.F90(6): error #6580: Name in only-list does not exist or is not accessible.   [FILE_EXIST]
   use             fms_mod, only: file_exist, check_nml_error, open_namelist_file, stdlog
----------------------------------^
```

### To Reproduce:
1. Run `datm_cdeps_lm4_oneapi` compile task or any tests that use it along with the spack-stack v2.1.0 stack used in PR #3174 .
2. Tests will fail. 

## Additional context
According to @RatkoVasic-NOAA , with the new FMS, we are getting errors in the LM4 land-surface driver code (ufs-weather-model/LM4-driver/, https://github.com/NOAA-GFDL/LM4-NUOPC-driver). That driver has not been updated with the new FMS. Ratko made some changes to ufs-weather-model/LM4-driver to get it to run:
```
        modified:   nuopc_cap/lm4_cap.F90
        modified:   nuopc_cap/lm4_driver.F90
        modified:   nuopc_cap/lm4_surface_flux.F90
```
and in ufs-weather-model/LM4-driver/LM4:
```
        modified:   shared/land_debug.F90
```
Ratko's changes can be viewed on Orion at: `/work/noaa/fv3-cam/rvasic/WM-SS-2.1.0/ufs-weather-model/`. However, these changes are mere suggestions--some changes are straightforward, but for some there may be a better way of doing it. 

@JustinPerket you're probably the one who would know best, so I'm tagging you here in the hope that you can take a look. That way we can avoid clogging up the main spack-stack v2.1.0 issue and PR and discuss any concerns here. 

## Output
My Orion logs with RT results on spack-stack v2.1.0 are available at: `/work2/noaa/epic/gpetro/orion/RTs/ufs-wm/stmp/gpetro/FV3_RT/rt_4074596`

**Comment by JustinPerket** [comment]
You beat me to the punch. I was about to reply on https://github.com/ufs-community/ufs-weather-model/issues/3067 that I found the same conclusion. I had made edits to a temporary branch on my fork at: 

https://github.com/JustinPerket/LM4-NUOPC-driver/tree/tmp/LM42025.03

As a first pass, the LM4 NUOPC cap itself seems to build fine. As you figured out the, underlying LM4 submodule is an older version also is not compatible with FMS 2025.03. We were in the process of providing an update to this verision, but it probably wouldn't be ready for the spack-stack v2.1.0 PR. 

This LM4-NUOPC-driver temp fork+branch points to an internal GFDL gitlab repo branch, so it is not accessible outside. I'm working with others at GFDL to see if this version would need further patching.

**Comment by gspetro-NOAA** [comment]
> You beat me to the punch. I was about to reply on [#3067](https://github.com/ufs-community/ufs-weather-model/issues/3067) that I found the same conclusion. I had made edits to a temporary branch on my fork at:
> 
> https://github.com/JustinPerket/LM4-NUOPC-driver/tree/tmp/LM42025.03
> 
> As a first pass, the LM4 NUOPC cap itself seems to build fine. As you figured out the, underlying LM4 submodule is an older version also is not compatible with FMS 2025.03. We were in the process of providing an update to this verision, but it probably wouldn't be ready for the spack-stack v2.1.0 PR.
> 
> This LM4-NUOPC-driver temp fork+branch points to an internal GFDL gitlab repo branch, so it is not accessible outside. I'm working with others at GFDL to see if this version would need further patching.

Great! Thanks for working on this! Do you have any idea what the timeline for the LM4 submodule update would be? If it is not ready for the v2.1.0 update, we will have to discuss a path forward with WM CMs. Currently it's listed as a dependency for the spack-stack v2.1.x PR, but waiting a month is very different from waiting a year, for example. In the first case, we'd probably wait; in the second, we'd need to find a different solution (e.g., temporary removal of the RT and/or LM4 submodule?).

**Comment by JustinPerket** [comment]
> Great! Thanks for working on this! Do you have any idea what the timeline for the LM4 submodule update would be? If it is not ready for the v2.1.0 update, we will have to discuss a path forward with WM CMs. Currently it's listed as a dependency for the spack-stack v2.1.x PR, but waiting a month is very different from waiting a year, for example. In the first case, we'd probably wait; in the second, we'd need to find a different solution (e.g., temporary removal of the RT and/or LM4 submodule?).

Sure thing! To clarify, for this issue, I'm not talking about upgrading LM4 from 4.0 to a new version, but taking a patched tag of LM4.0 we have have on the internal GFDL gitlab. I'm now able to build and run with this LM4 tag, and my edits to LM4-NUOPC-driver. A bit of clean up and regression testing should hopefully take less than a month, much less a year!

[NOAA-GFDL/LM4](https://github.com/NOAA-GFDL/lm4) has previously only been used for publication releases, so we'll have confirm we have an appropriate branch strategy to place this tag on github. This is a bit of a test case for the repo.

**Comment by gspetro-NOAA** [comment]
> Sure thing! To clarify, for this issue, I'm not talking about upgrading LM4 from 4.0 to a new version, but taking a patched tag of LM4.0 we have have on the internal GFDL gitlab. I'm now able to build and run with this LM4 tag, and my edits to LM4-NUOPC-driver. A bit of clean up and regression testing should hopefully take less than a month, much less a year!
> 
> [NOAA-GFDL/LM4](https://github.com/NOAA-GFDL/lm4) has previously only been used for publication releases, so we'll have confirm we have an appropriate branch strategy to place this tag on github. This is a bit of a test case for the repo.

Great! Then there shouldn't be any problem. The spack-stack PR isn't fully open yet anyway because there is a LOT of testing to do on multiple systems and components. I wouldn't go so far as to say "take your time," but we're not trying to merge the spack-stack PR next week either, so I think we can wait for this work to be done. Just let me know if the timeline changes, and we can reassess if need be.

**Comment by JustinPerket** [comment]
I have the draft PR https://github.com/NOAA-GFDL/LM4-NUOPC-driver/pull/5 ready when your UFS PR is. 
 (I neglected to see there was a newer commit on the same branch for [/NOAA-GFDL/LM4](https://github.com/NOAA-GFDL/lm4 that would work with FMS 2025.03, so ignore my previous comment.

It does not change baseline with current UFS develop, but does when run with https://github.com/ufs-community/ufs-weather-model/pull/3174 . A small number of points in the restart files change by > 0.001%, no crazy absolute changes catch my eye.  If this is in line with the expected baseline changes mentioned in that PR, I think we're good.

**Comment by dustinswales** [comment]
FYI. This was added to the MPAS dycore project board for some unknown reason.
Removing.

**Comment by gspetro-NOAA** [comment]
> I have the draft PR [NOAA-GFDL/LM4-NUOPC-driver#5](https://github.com/NOAA-GFDL/LM4-NUOPC-driver/pull/5) ready when your UFS PR is. (I neglected to see there was a newer commit on the same branch for [/NOAA-GFDL/LM4](https://github.com/NOAA-GFDL/lm4 that would work with FMS 2025.03, so ignore my previous comment.
> 
> It does not change baseline with current UFS develop, but does when run with [#3174](https://github.com/ufs-community/ufs-weather-model/pull/3174) . A small number of points in the restart files change by > 0.001%, no crazy absolute changes catch my eye. If this is in line with the expected baseline changes mentioned in that PR, I think we're good.

@JustinPerket Thanks! I've added it to PR #3174 . Could you take a look to make sure everything looks ok?

**Comment by JustinPerket** [comment]
Looks fine. It's the same commit now, but I had put a different branch name, `JustinPerket:LM4_FMS2025.03`, on the https://github.com/NOAA-GFDL/LM4-NUOPC-driver/pull/5 PR, just in case I made any temporary changes to JustinPerket:tmp/LM42025.03. I won't delete or change it now.

Since https://github.com/NOAA-GFDL/LM4-NUOPC-driver/pull/5 satisfies the FMS issue, I check again it doesn't show any changes with UFS develop on Gaea and Orion for datm_cdeps_lm4_gswp3_intel / datm_cdeps_lm4_gswp3_rst_intel, and then merge.

**Comment by gspetro-NOAA** [comment]
Yes, I was a little confused because your LM4_FMS2025.03 branch is in the PR, so that's what I added to my PR, but then you were talking about the tmp/LM4_2025.03 branch, which seemed to have the same head commit. Which one should I be using?

**Comment by JustinPerket** [comment]
> Yes, I was a little confused because your LM4_FMS2025.03 branch is in the PR, so that's what I added to my PR, but then you were talking about the tmp/LM4_2025.03 branch, which seemed to have the same head commit. Which one should I be using?

My bad for having the 2 similar branches floating around. I now merged https://github.com/NOAA-GFDL/LM4-NUOPC-driver/pull/5, so whenever you're ready you can revert LM4 driver back to 
```
  url = https://github.com/NOAA-GFDL/LM4-NUOPC-driver
  branch = develop
```
now with head  https://github.com/NOAA-GFDL/LM4-NUOPC-driver/commit/513b6731251

( I think I see https://github.com/ufs-community/ufs-weather-model/pull/3174/changes/0b150946a2428fe8854defb1c7dfdb6129bab687 shows `tmp/LM4_2025.03` , but I'll keep both branches on my fork unmodified. )

I hope this resolves the compile FMS issue. If there's anything else that come up with the spack-stack 2.1 PR, let me know!
