### PR TITLE
Update LM4-driver hash

### LINKED ISSUE #3212: `datm_cdeps_lm4_oneapi` compile failure on Orion w/spack-stack v2.1.0
## Description
On Orion, all RT configurations compile with spack-stack v2.1.0 except `datm_cdeps_lm4_oneapi`, which fails due to errors like:
```
/work2/noaa/epic/gpetro/orion/RTs/ufs-wm/pretests/3174/LM4-driver/nuopc_cap/lm4_surface_flux.F90(5): error #6580: Name in only-list does not exist or is not accessible.   [CLOSE_FILE]
   use             fms_mod, only: close_file, mpp_pe, mpp_root_pe, write_version_number
----------------------------------^
/work2/noaa/epic/gpetro/orion/RTs/ufs-wm/pretests/3174/LM4-driver/nuopc_cap/lm4_surface_flux.F90(6): error #6580: Name in only-list does not exist or is not accessible.   [FILE_EXIST]
   use             fms_mod, only: file_exist, check_nml_error, open_namelist_file, stdlog
----------------------------------^
```

### To Reproduce:
1. Run `datm_cdeps_lm4_oneapi` compile task or any tests that use it along with the spack-stack v2.1.0 stack used in PR #3174 .
2. Tests will fail. 

## Additional context
According to @RatkoVasic-NOAA , with the new FMS, we are getting errors in the LM4 land-surface driver code (ufs-weather-model/LM4-driver/, https://github.com/NOAA-GFDL/LM4-NUOPC-driver). That driver has not been updated with the new FMS. Ratko made some changes to ufs-weather-model/LM4-driver to get it to run:
```
        modified:   nuopc_cap/lm4_cap.F90
        modified:   nuopc_cap/lm4_driver.F90
        modified:   nuopc_cap/lm4_surface_flux.F90
```
and in ufs-weather-model/LM4-driver/LM4:
```
        modified:   shared/land_debug.F90
```
Ratko's changes can be viewed on Orion at: `/work/noaa/fv3-cam/rvasic/WM-SS-2.1.0/ufs-weather-model/`. However, these changes are mere suggestions--some changes are straightforward, but for some there may be a better way of doing it. 

@JustinPerket you're probably the one who would know best, so I'm tagging you here in the hope that you can take a look. That way we can avoid clogging up the main spack-stack v2.1.0 issue and PR and discuss any concerns here. 

## Output
My Orion logs with RT results on spack-stack v2.1.0 are available at: `/work2/noaa/epic/gpetro/orion/RTs/ufs-wm/stmp/gpetro/FV3_RT/rt_4074596`

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
## Commit Queue Requirements:
- [x] This PR addresses a relevant WM issue (if not, create an issue). 
- [x] All subcomponent pull requests (if any) have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines), preferably on Ursa (Derecho or Hercules are acceptable alternatives). **Exceptions:** documentation-only PRs, CI-only PRs, etc.
   - [x] Commit log file w/full results from RT suite run (if applicable).
   - [x] Verify that `test_changes.list` indicates which tests, if any, are changed by this PR. Commit `test_changes.list`, even if it is empty.
- [ ] Fill out all sections of this template.

---

## Description:
- Update the LM4-driver hash to work with FMS 2025.03. This hash is required for the upgrade to spack-stack v2.1.0 and has also been tested with those compilers via PR #3174 . 
- Update rt.conf to run lm4 tests on Ursa & Orion (rather than Hera & Orion).

### Commit Message:
```
* UFSWM - Update LM4-driver hash
  * LM4-driver - Update LM4 hash
```

### Priority:
- [ ] Critical Bugfix: Reason
- [X] High: Repo_check CI will fail until this PR is merged
- [ ] Normal

### UFSWM:
* Closes #3212 

### Sub component Pull Requests:
* LM4-driver: https://github.com/NOAA-GFDL/LM4-NUOPC-driver/pull/5

### UFSWM Blocking Dependencies:

- [ ] Blocked by #
- [X] None

### Documentation:

- [ ] Documentation update required. 
   - [ ] Relevant updates are included with this PR. 
   - [ ] A WM issue has been opened to track the need for a documentation update; a person responsible for submitting the update has been assigned to the issue (link issue).
- [X] Documentation update NOT required. 
   - Explanation: Component update

---
### Regression Test Changes (Please commit test_changes.list):
- [x] PR Adds New Tests/Baselines. Only for LM4 test (datm_cdeps_lm4_gswp3_intel) on Ursa because it hasn't been run there before. Baseline already exists on Orion and doesn't run on other platforms. 
- [ ] PR Updates/Changes Baselines. 
- [ ] No Baseline Changes.

### Input data Changes:

- [X] None.
- [ ] PR adds input data.
- [ ] PR changes existing input data.

### Library Changes/Upgrades:

- [ ] Required
  * Library names w/versions:
  * Git Stack Issue (JCSDA/spack-stack#)
- [X] No Updates
  
---

## Testing Log:
- RDHPCS
  - [ ] Orion
  - [ ] Hercules
  - [ ] GaeaC6
  - [ ] Derecho
  - [ ] Ursa
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- [ ] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by gspetro-NOAA** [comment]
Merged via #3203 .
