### PR TITLE
make ufs-weather-model compile on native AWS (#3203) // Removing hard coded baseline date (#3214) // Add/update FAQs for user guide (#3219) // Update LM4-driver hash (#3228)

### LINKED ISSUE #3202: make ufs-weather-model compile on native AWS
## Description
In order for more general users to use ufs-weather-model, we want to make ufs-weather-model being able to compile on native AWS (as a new computing platform, or machine). This is a part of making Global-Workflow porting to native AWS.

## Solution
Add new modulefiles to use spack-stack on native-AWS
way to detect native AWS machine
use module files for native AWS.

## Alternatives
None

## Related to
UPP: https://github.com/NOAA-EMC/UPP/issues/1506

### LINKED ISSUE #3212: `datm_cdeps_lm4_oneapi` compile failure on Orion w/spack-stack v2.1.0
## Description
On Orion, all RT configurations compile with spack-stack v2.1.0 except `datm_cdeps_lm4_oneapi`, which fails due to errors like:
```
/work2/noaa/epic/gpetro/orion/RTs/ufs-wm/pretests/3174/LM4-driver/nuopc_cap/lm4_surface_flux.F90(5): error #6580: Name in only-list does not exist or is not accessible.   [CLOSE_FILE]
   use             fms_mod, only: close_file, mpp_pe, mpp_root_pe, write_version_number
----------------------------------^
/work2/noaa/epic/gpetro/orion/RTs/ufs-wm/pretests/3174/LM4-driver/nuopc_cap/lm4_surface_flux.F90(6): error #6580: Name in only-list does not exist or is not accessible.   [FILE_EXIST]
   use             fms_mod, only: file_exist, check_nml_error, open_namelist_file, stdlog
----------------------------------^
```

### To Reproduce:
1. Run `datm_cdeps_lm4_oneapi` compile task or any tests that use it along with the spack-stack v2.1.0 stack used in PR #3174 .
2. Tests will fail. 

## Additional context
According to @RatkoVasic-NOAA , with the new FMS, we are getting errors in the LM4 land-surface driver code (ufs-weather-model/LM4-driver/, https://github.com/NOAA-GFDL/LM4-NUOPC-driver). That driver has not been updated with the new FMS. Ratko made some changes to ufs-weather-model/LM4-driver to get it to run:
```
        modified:   nuopc_cap/lm4_cap.F90
        modified:   nuopc_cap/lm4_driver.F90
        modified:   nuopc_cap/lm4_surface_flux.F90
```
and in ufs-weather-model/LM4-driver/LM4:
```
        modified:   shared/land_debug.F90
```
Ratko's changes can be viewed on Orion at: `/work/noaa/fv3-cam/rvasic/WM-SS-2.1.0/ufs-weather-model/`. However, these changes are mere suggestions--some changes are straightforward, but for some there may be a better way of doing it. 

@JustinPerket you're probably the one who would know best, so I'm tagging you here in the hope that you can take a look. That way we can avoid clogging up the main spack-stack v2.1.0 issue and PR and discuss any concerns here. 

## Output
My Orion logs with RT results on spack-stack v2.1.0 are available at: `/work2/noaa/epic/gpetro/orion/RTs/ufs-wm/stmp/gpetro/FV3_RT/rt_4074596`

### PR DESCRIPTION
**Pull request by weihuang-jedi**
## Commit Queue Requirements:
- [x] This PR addresses a relevant WM issue (#3202). 
- [x] All subcomponent pull requests (if any) have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines), preferably on Ursa (Derecho or Hercules are acceptable alternatives). **Exceptions:** documentation-only PRs, CI-only PRs, etc.
   - [x] Commit log file w/full results from RT suite run (if applicable).
   - [x] Verify that `test_changes.list` indicates which tests, if any, are changed by this PR. Commit `test_changes.list`, even if it is empty.
- [ ] Fill out all sections of this template.

### #3203
In order for more general users to use ufs-weather-model, we want to make ufs-weather-model being able to compile on native AWS (as a new computing platform, or machine). This is a part of making Global-Workflow porting to native AWS.

### #3214 
Remove hard coded base line date associated with Parallelworks (NOAACloud) regression test CI script

### #3219 
Adding new and updating old FAQs

### #3228 
Update the LM4-driver hash to work with FMS 2025.03. This hash is required for the upgrade to spack-stack v2.1.0 and has also been tested with those compilers via PR https://github.com/ufs-community/ufs-weather-model/pull/3174 .
Update rt.conf to run lm4 tests on Ursa & Orion (rather than Hera & Orion).

### Commit Message:
```
* UFSWM - Make UFS WM compile on native AWS
* UFSWM - Removing hard coded baseline date
* UFSWM - Update FAQs
* UFSWM - Update LM4-driver hash
  * LM4-driver - Update LM4 hash
``` 

### Priority:
- [x ] Normal

### UFSWM:
* Closes #3202
* Closes #3212 

### Sub component Pull Requests:
* LM4-driver: https://github.com/NOAA-GFDL/LM4-NUOPC-driver/pull/5

### UFSWM Blocking Dependencies:
- [ x] None

### Documentation:
- [ ] Documentation update required. 
   - [ ] Relevant updates are included with this PR. 
   - [ ] A WM issue has been opened to track the need for a documentation update; a person responsible for submitting the update has been assigned to the issue (link issue).
- [ ] Documentation update NOT required. 
   - Explanation: 

---
### Regression Test Changes (Please commit test_changes.list):
- PR Adds New Tests/Baselines. Only for LM4 test (datm_cdeps_lm4_gswp3_intel) on Ursa because it hasn't been run there before. Baseline already exists on Orion and doesn't run on other platforms (formerly ran on Hera).

### Input data Changes:
- [ x] None.

### Library Changes/Upgrades:
- [ x] No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Orion
  - [x] Hercules
  - [x] GaeaC6
  - [ ] Derecho
  - [x] Ursa
- WCOSS2
  - [x] Dogwood/Cactus
  - [x] Acorn
- [ ] CI
- [x] opnReqTest (complete task if unnecessary)
- [x ] native-AWS
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

### CODE REVIEW

File: tests/detect_machine.sh [hunk 1]
```diff
@@ -55,6 +55,13 @@ case $(hostname -f) in
   derecho7.hsn.de.hpc.ucar.edu) MACHINE_ID=derecho ;; ### derecho7
   derecho8.hsn.de.hpc.ucar.edu) MACHINE_ID=derecho ;; ### derecho8
   
+  ip-*) MACHINE_ID=aws-ec2 ;; ### aws-ec2
+  compute-dy-*) MACHINE_ID=aws-ec2 ;; ### aws-ec2
+  processing-dy-*) MACHINE_ID=aws-ec2 ;; ### aws-ec2
+
+  login[1-4].frontera.tacc.utexas.edu) MACHINE_ID=frontera ;; ### frontera1-4
+  c*.frontera.tacc.utexas.edu) MACHINE_ID=frontera ;; ### frontera compute 
+
```
Comment (gspetro-NOAA) [inline tests/detect_machine.sh]: This frontera section should be removed since there is no longer support for that machine. 
```suggestion
```

**Comment by BrianCurtis-NOAA** [comment]
I can't push to this repo, WCOSS2 log is on Ursa at: /scratch4/NCEPDEV/nems/Brian.Curtis

**Comment by BrianCurtis-NOAA** [comment]
> I can't push to this repo, WCOSS2 log is on Ursa at: /scratch4/NCEPDEV/nems/Brian.Curtis

Acorn logs are there as well, now.

**Comment by BrianCurtis-NOAA** [comment]
> > I can't push to this repo, WCOSS2 log is on Ursa at: /scratch4/NCEPDEV/nems/Brian.Curtis
> 
> Acorn logs are there as well, now.

I also moved them to /scratch4/NCEPDEV/stmp/Brian.Curtis which might be more accessible.

**Comment by gspetro-NOAA** [comment]
Noting that we will skip RTs on Derecho due to 2-day maintenance.

**Review by gspetro-NOAA — APPROVED** [review]

**Review by dpsarmie — APPROVED** [review]

**Review by FernandoAndrade-NOAA — APPROVED** [review]
