### PR TITLE
Update CICE to CICE-Consortium (2024-05-01)+update mom6 to its main repo. 20240508 commit #2275

### LINKED ISSUE #78: Sync w/ Consortium/main
The following PRs have been merged at the upstream and should be brought to our fork

- https://github.com/CICE-Consortium/CICE/pull/935. This adds a namelist variable to control whether coords are written to history files
- https://github.com/CICE-Consortium/CICE/pull/938. This fixes a typo w/in a CESMCOUPLED block
- https://github.com/CICE-Consortium/CICE/pull/936. This sets calendar information to be consistent w/ the namelist and vice versa
- https://github.com/CICE-Consortium/CICE/pull/940. This adds new diagnostics field for snow volume tendencies due to thermo and dynamics
- https://github.com/CICE-Consortium/CICE/pull/943. This ensures that individual history streams have unique filenames. If they do not, then streams will overwrite each other. With this change, abort in that case.

### LINKED ISSUE #2274: update MOM6 to its main repo. 20240508 commit
MOM6 main repo. was updated on 20240508. This is a minor enhancement for the original "remove compiling warning" PR (see detail at https://github.com/mom-ocean/MOM6/pull/1623). We need to pull it back to dev/emc.

### PR DESCRIPTION
**Pull request by NickSzapiro-NOAA**
## Commit Queue Requirements:

- [x] Fill out all sections of this template.
- [x] All sub component pull requests have been reviewed by their code managers.
- [x] Run the full Intel+GNU RT suite (compared to current baselines) on either Hera/Derecho/Hercules
- [x] Commit 'test_changes.list' from previous step
---
## Description:

https://github.com/CICE-Consortium/CICE/pull/935 This adds a namelist variable to control whether coords are written to history files
https://github.com/CICE-Consortium/CICE/pull/936 This sets calendar information to be consistent w/ the namelist and vice versa
https://github.com/CICE-Consortium/CICE/pull/938 This fixes a typo w/in a CESMCOUPLED block
https://github.com/CICE-Consortium/CICE/pull/939 and https://github.com/CICE-Consortium/CICE/pull/942 Port to Carpenter
https://github.com/CICE-Consortium/CICE/pull/940 This adds new diagnostics field for snow volume tendencies due to thermo and dynamics
https://github.com/CICE-Consortium/CICE/pull/943 This ensures that individual history streams have unique filenames. If they do not, then streams will overwrite each other. With this change, abort in that case.
https://github.com/CICE-Consortium/CICE/pull/948 Fix Github Actions for macos system update
https://github.com/mom-ocean/MOM6/pull/1623 Address compiler warning

### Commit Message:

```
* UFSWM - Update CICE to CICE-Consortium (2024-05-01) and mom6 to its main repo (2024-05-08)
  * CICE - Update CICE to CICE-Consortium (2024-05-01)
  * MOM6 - Update mom6 to its main repo. 20240508 commit
```

### Priority:

* Normal

### UFSWM:

* Closes https://github.com/NOAA-EMC/CICE/issues/78
* Closes https://github.com/ufs-community/ufs-weather-model/issues/2274

### Sub component Pull Requests:

* CICE: https://github.com/NOAA-EMC/CICE/pull/79
* MOM6: https://github.com/NOAA-EMC/MOM6/pull/134

### UFSWM Blocking Dependencies:

* None

---
### Regression Test Changes (Please commit test_changes.list):

* No Baseline Changes.
hera log and test_changes.list in commit history

### Input data Changes:

* None.

### Library Changes/Upgrades:

* No Updates
  
---

## Testing Log:
- RDHPCS
  - [x] Hera
  - [x] Orion
  - [x] Hercules
  - [x] Jet
  - [x] Gaea
  - [x] Derecho
- WCOSS2
  - [x] Dogwood/Cactus
  - [ ] Acorn
- [x] CI
- [ ] opnReqTest (complete task if unnecessary)

### CODE REVIEW

**Comment by jkbk2004** [comment]
@pjpegion @jiandewang I merged in #2271 and #2275 to this pr. Can you check?

**Comment by jiandewang** [comment]
MOM is pointing to the right branch. Thanks

**Comment by BrianCurtis-NOAA** [comment]
As per instructions in the previous pull request (see: https://github.com/ufs-community/ufs-weather-model/pull/2215#issuecomment-2102701561), @jkbk2004 and team: when you combine multiple pull requests together its extremely important to bring all of the information from the outside PR's into the combined PR.

**Comment by jkbk2004** [comment]
It's strange to see compile error on gaea with physics. It ran ok on hera/orion/hercules though.
```
/gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(236): error #8\
284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type charact\
er or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
      CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
-----------^
compilation aborted for /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/g\
cycle.F90 (code 1)
make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:296: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir\
/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90.o] Error 1
```

**Comment by jkbk2004** [comment]
> As per instructions in the previous pull request (see: [#2215 (comment)](https://github.com/ufs-community/ufs-weather-model/pull/2215#issuecomment-2102701561)), @jkbk2004 and team: when you combine multiple pull requests together its extremely important to bring all of the information from the outside PR's into the combined PR.

@BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA Thanks for the note! We will make sure to pull out all the PR information when PR is ready.

**Comment by BrianCurtis-NOAA** [comment]
> > As per instructions in the previous pull request (see: [#2215 (comment)](https://github.com/ufs-community/ufs-weather-model/pull/2215#issuecomment-2102701561)), @jkbk2004 and team: when you combine multiple pull requests together its extremely important to bring all of the information from the outside PR's into the combined PR.
> 
> @BrianCurtis-NOAA @zach1221 @FernandoAndrade-NOAA Thanks for the note! We will make sure to pull out all the PR information when PR is ready.

This should be completed _before_ the PR starts testing. Testing is the final stage of the PR process before merge.

**Comment by jkbk2004** [comment]
> It's strange to see compile error on gaea with physics. It ran ok on hera/orion/hercules though.
> 
> ```
> /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(236): error #8\
> 284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type charact\
> er or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
>       CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
> -----------^
> compilation aborted for /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/g\
> cycle.F90 (code 1)
> make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:296: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir\
> /physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90.o] Error 1
> ```

@pjpegion The gaea build failures came from #2271. I am detaching #2271.

**Comment by BrianCurtis-NOAA** [comment]
> > It's strange to see compile error on gaea with physics. It ran ok on hera/orion/hercules though.
> > ```
> > /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(236): error #8\
> > 284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type charact\
> > er or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
> >       CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
> > -----------^
> > compilation aborted for /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/g\
> > cycle.F90 (code 1)
> > make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:296: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir\
> > /physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90.o] Error 1
> > ```
> 
> @pjpegion The gaea build failures came from #2271. I am detaching #2271.

@jkbk2004 can you please elaborate on how this comes from #2271? You said it ran fine on three other platforms. This leans to being a gaea issue, not a PR issue.

**Comment by jkbk2004** [comment]
> > > It's strange to see compile error on gaea with physics. It ran ok on hera/orion/hercules though.
> > > ```
> > > /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(236): error #8\
> > > 284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type charact\
> > > er or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
> > >       CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
> > > -----------^
> > > compilation aborted for /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/g\
> > > cycle.F90 (code 1)
> > > make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:296: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir\
> > > /physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90.o] Error 1
> > > ```
> > 
> > 
> > @pjpegion The gaea build failures came from #2271. I am detaching #2271.
> 
> @jkbk2004 can you please elaborate on how this comes from #2271? You said it ran fine on three other platforms. This leans to being a gaea issue, not a PR issue.

If I detach PR 2271, it runs ok even on gaea. Strange PR 2271 has nothing to do with physics but it looks like there is a confliction.

**Comment by jkbk2004** [comment]
Anyway, I feel comfortable to say this PR combining with #2275 is ready. @zach1221 @FernandoAndrade-NOAA can you pick up from here and complete the PR templates ?

**Comment by BrianCurtis-NOAA** [comment]
> > > > It's strange to see compile error on gaea with physics. It ran ok on hera/orion/hercules though.
> > > > ```
> > > > /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(236): error #8\
> > > > 284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type charact\
> > > > er or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
> > > >       CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
> > > > -----------^
> > > > compilation aborted for /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/g\
> > > > cycle.F90 (code 1)
> > > > make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:296: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir\
> > > > /physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90.o] Error 1
> > > > ```
> > > 
> > > 
> > > @pjpegion The gaea build failures came from #2271. I am detaching #2271.
> > 
> > 
> > @jkbk2004 can you please elaborate on how this comes from #2271? You said it ran fine on three other platforms. This leans to being a gaea issue, not a PR issue.
> 
> If I detach PR 2271, it runs ok even on gaea. Strange PR 2271 has nothing to do with physics but it looks like there is a confliction.

You're not really answering the question here: Did you do any work towards finding out WHY it failed on Gaea when it didn't fail on any other platform?

What has happened here is a waste of resources on Hera, Orion, Hercules, WCOSS2, Acorn. Since you've just detached a PR without a reason why, we all have to run this whole PR again.

**Comment by jkbk2004** [comment]
> > > > > It's strange to see compile error on gaea with physics. It ran ok on hera/orion/hercules though.
> > > > > ```
> > > > > /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(236): error #8\
> > > > > 284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type charact\
> > > > > er or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
> > > > >       CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
> > > > > -----------^
> > > > > compilation aborted for /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/g\
> > > > > cycle.F90 (code 1)
> > > > > make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:296: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir\
> > > > > /physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90.o] Error 1
> > > > > ```
> > > > 
> > > > 
> > > > @pjpegion The gaea build failures came from #2271. I am detaching #2271.
> > > 
> > > 
> > > @jkbk2004 can you please elaborate on how this comes from #2271? You said it ran fine on three other platforms. This leans to being a gaea issue, not a PR issue.
> > 
> > 
> > If I detach PR 2271, it runs ok even on gaea. Strange PR 2271 has nothing to do with physics but it looks like there is a confliction.
> 
> You're not really answering the question here: Did you do any work towards finding out WHY it failed on Gaea when it didn't fail on any other platform?
> 
> What has happened here is a waste of resources on Hera, Orion, Hercules, WCOSS2, Acorn. Since you've just detached a PR without a reason why, we all have to run this whole PR again.

I completely agree current RT test cases (240 case and 8 or 9 platforms) are too intensive for pre-tests or daily runs.

**Comment by BrianCurtis-NOAA** [comment]
> > > > > > It's strange to see compile error on gaea with physics. It ran ok on hera/orion/hercules though.
> > > > > > ```
> > > > > > /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(236): error #8\
> > > > > > 284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type charact\
> > > > > > er or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
> > > > > >       CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
> > > > > > -----------^
> > > > > > compilation aborted for /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/g\
> > > > > > cycle.F90 (code 1)
> > > > > > make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:296: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir\
> > > > > > /physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90.o] Error 1
> > > > > > ```
> > > > > 
> > > > > 
> > > > > @pjpegion The gaea build failures came from #2271. I am detaching #2271.
> > > > 
> > > > 
> > > > @jkbk2004 can you please elaborate on how this comes from #2271? You said it ran fine on three other platforms. This leans to being a gaea issue, not a PR issue.
> > > 
> > > 
> > > If I detach PR 2271, it runs ok even on gaea. Strange PR 2271 has nothing to do with physics but it looks like there is a confliction.
> > 
> > 
> > You're not really answering the question here: Did you do any work towards finding out WHY it failed on Gaea when it didn't fail on any other platform?
> > What has happened here is a waste of resources on Hera, Orion, Hercules, WCOSS2, Acorn. Since you've just detached a PR without a reason why, we all have to run this whole PR again.
> 
> I completely agree current RT test cases (240 case and 8 or 9 platforms) are too intensive for pre-tests or daily runs.

Please, can you describe the debugging you did with the failure on Gaea?

**Comment by jkbk2004** [comment]
> > > > > > > It's strange to see compile error on gaea with physics. It ran ok on hera/orion/hercules though.
> > > > > > > ```
> > > > > > > /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90(236): error #8\
> > > > > > > 284: If the actual argument is scalar, the dummy argument shall be scalar unless the actual argument is of type charact\
> > > > > > > er or is an element of an array that is not assumed shape, pointer, or polymorphic.   [SIG1T]
> > > > > > >       CALL SFCCYCLE (9998, npts, max(lsoil,lsoil_lsm), sig1t, fhcyc, &
> > > > > > > -----------^
> > > > > > > compilation aborted for /gpfs/f5/epic/scratch/Jong.Kim/rt-2259/FV3/ccpp/physics/physics/Interstitials/UFS_SCM_NEPTUNE/g\
> > > > > > > cycle.F90 (code 1)
> > > > > > > make[2]: *** [FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir/build.make:296: FV3/ccpp/physics/CMakeFiles/ccpp_physics.dir\
> > > > > > > /physics/Interstitials/UFS_SCM_NEPTUNE/gcycle.F90.o] Error 1
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > @pjpegion The gaea build failures came from #2271. I am detaching #2271.
> > > > > 
> > > > > 
> > > > > @jkbk2004 can you please elaborate on how this comes from #2271? You said it ran fine on three other platforms. This leans to being a gaea issue, not a PR issue.
> > > > 
> > > > 
> > > > If I detach PR 2271, it runs ok even on gaea. Strange PR 2271 has nothing to do with physics but it looks like there is a confliction.
> > > 
> > > 
> > > You're not really answering the question here: Did you do any work towards finding out WHY it failed on Gaea when it didn't fail on any other platform?
> > > What has happened here is a waste of resources on Hera, Orion, Hercules, WCOSS2, Acorn. Since you've just detached a PR without a reason why, we all have to run this whole PR again.
> > 
> > 
> > I completely agree current RT test cases (240 case and 8 or 9 platforms) are too intensive for pre-tests or daily runs.
> 
> Please, can you describe the debugging you did with the failure on Gaea?
see the attached test result working fine if I detach PR2271. We need to move this debugging discussion to #2271.
[RegressionTests_gaea.log](https://github.com/ufs-community/ufs-weather-model/files/15276296/RegressionTests_gaea.log)

**Comment by DusanJovic-NOAA** [comment]
@jkbk2004 Which test failed to compile on gaea?

**Comment by jkbk2004** [comment]
> @jkbk2004 Which test failed to compile on gaea?

@DusanJovic-NOAA They are rap_control_debug_dyn32_phy32 intel, hrrr_control_debug_dyn32_phy32 intel, conus13km_debug intel, conus13km_debug_qr intel, conus13km_debug_2threads intel, conus13km_radar_tten_debug intel. I will move to #2271 to follow on.

**Comment by jiandewang** [comment]
@zach1221 I am heading for a dental appt. now, so if it comes to the point that needs MOM6 merging, please bear me a bit delay.

**Comment by jiandewang** [comment]
@zach1221 my dental appt. finished earlier than expected. Back to business now. Let me know when its time I shall do MOM6 merging

**Comment by BrianCurtis-NOAA** [comment]
At this point if we're waiting on Acorn only, then skip it. Lots of testing SA work going on Acorn, and it's currently not running there.

**Comment by FernandoAndrade-NOAA** [comment]
Ok, I'll leave a note in the sub PRs to continue with the merge process.

**Review by DeniseWorthen — DISMISSED** [review]
CICE hash is correct.

**Comment by jiandewang** [comment]
just merged MOM6 woth hash 3bcfbbea

**Comment by NickSzapiro-NOAA** [comment]
@DeniseWorthen @jiandewang Updated CICE and MOM6 hashes

**Review by BrianCurtis-NOAA — APPROVED** [review]
Hashes look good on MOM6 and CICE.

**Review by jkbk2004 — APPROVED** [review]
